version: "3.9"

services:
  # ── Base de données MongoDB ──────────────────────────────────────
  mongo:
    image: mongo:7.0
    container_name: todo_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # ── API ASP.NET Core ─────────────────────────────────────────────
  api:
    build: .
    container_name: todo_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - MongoDbSettings__ConnectionString=mongodb://mongo:27017
      - MongoDbSettings__DatabaseName=TodoDb
      - MongoDbSettings__TodosCollectionName=todos
      - JwtSettings__SecretKey=TodoApiSecretKey2026AissataSY_SuperSecure!
      - JwtSettings__Issuer=TodoApi
      - JwtSettings__Audience=TodoApiUsers
      - JwtSettings__ExpirationMinutes=60
    depends_on:
      - mongo

volumes:
  mongo_data:
